### ISSUE TITLE
Error: Package subpath './compiler.js' is not defined by "exports" in node_modules/svelte/package.json

### ISSUE THREAD

**Issue by vulcangz** [vulcangz/svelte-baidumaps#7]
No errors in local build, but errors during actions workflow on GitHub

<details>
<summary>Error.</summary>

```
Run npm test

> @vulcangz/svelte-baidumaps@0.1.2 test /home/runner/work/svelte-baidumaps/svelte-baidumaps
> start-server-and-test dev http://localhost:5000 cy:run

1: starting server using command "npm run dev"
and when url "[ 'http://localhost:5000' ]" is responding with HTTP status code 200
running tests using command "npm run cy:run"


> @vulcangz/svelte-baidumaps@0.1.2 dev /home/runner/work/svelte-baidumaps/svelte-baidumaps
> rollup -c -w

[!] Error: Package subpath './compiler.js' is not defined by "exports" in /home/runner/work/svelte-baidumaps/svelte-baidumaps/node_modules/svelte/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './compiler.js' is not defined by "exports" in /home/runner/work/svelte-baidumaps/svelte-baidumaps/node_modules/svelte/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:508:3)
    at resolveExports (internal/modules/cjs/loader.js:424:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/svelte-baidumaps/svelte-baidumaps/node_modules/rollup-plugin-svelte/index.js:12:4)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

Error: server closed unexpectedly
    at ChildProcess.onClose (/home/runner/work/svelte-baidumaps/svelte-baidumaps/node_modules/start-server-and-test/src/index.js:69:14)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm ERR! Test failed.  See above for more details.
Error: Process completed with exit code 1.
```
</details>

**Comment by vulcangz** [comment]
# sveltejs/svelte#5665
